#!/usr/bin/env python3
"""build_brain.py — re-runnable, manifest-driven build of the coach's value-prop
+ stakeholder corpus.

Pattern (from the THJ TKR_GENERIC derivation, thj plan 26-6-18): author intent on
the SOURCE — here, the MANIFEST below — never hand-edit the target. Re-run anytime
to track the latest source docs with zero drift. The corpus is *generated*; a
hand-maintained corpus rots the moment a source doc improves.

Pathways
--------
  INPUT      ~/repo_docs/thj/<manifest path>            (override: COACH_BRAIN_SOURCE_ROOT)
             — every MANIFEST entry is a path under this root. A directory entry
               pulls every *.md beneath it (recursive); a file entry pulls just it.
  ASSEMBLED  services/coach/brain/coach_brain_corpus.md  (inspectable, gitignored)
             — all sources concatenated into ONE big document with provenance
               headers, the artifact a human can eyeball before it ships.
  CORPUS     kb Postgres reference_docs + reference_doc_chunks                (ingest)
             — one logical doc "THJ Coach Brain — value-prop + stakeholders",
               chunked + embedded (shared-svcs), upserted idempotently so a
               re-run replaces cleanly.

Fail-closed: a MANIFEST entry that does not resolve to at least one file HARD-FAILS
the build (non-zero exit, names the entry) — never ships a partial brain. An empty
MANIFEST exits 2 with guidance rather than silently building nothing.

Usage
-----
  uv run python services/coach/build_brain.py              # assemble + ingest
  uv run python services/coach/build_brain.py --dry-run    # assemble + write big doc only
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Pathways
# ---------------------------------------------------------------------------

SOURCE_ROOT = Path(
    os.environ.get("COACH_BRAIN_SOURCE_ROOT", "~/repo_docs/thj")
).expanduser()

OUTPUT_PATH = Path(__file__).parent / "brain" / "coach_brain_corpus.md"

CORPUS_TITLE = "THJ Coach Brain — value-prop + stakeholders"

# ---------------------------------------------------------------------------
# MANIFEST — the authored intent (analog of TKR_GENERIC's per-component `generic`
# flag). Each entry is a path UNDER SOURCE_ROOT (~/repo_docs/thj). They are ALL
# repo_docs/thj folders or files. A dir → every *.md beneath it; a file → just it.
#
# >>> OPEN-ENDED: fill in once the exact value-prop + stakeholder doc set is known.
# >>> Leave the numbering — we edit this list, nothing else, to refresh the brain.
#
# Likely homes to draw from (commented; uncomment/refine when confirmed):
#   project/            business/           mvp/
#   sales-plays/        stakeholders/       surgeon-perspective/
#   voice/              governance/
# ---------------------------------------------------------------------------
MANIFEST: list[str] = [
    # 1.
    # 2.
    # 3.
    # 4.
    # 5.
]


# ---------------------------------------------------------------------------
# 1. Resolve the manifest → concrete source files (fail-closed)
# ---------------------------------------------------------------------------


def resolve_sources(manifest: list[str], root: Path) -> list[Path]:
    """Expand each manifest entry to one-or-more *.md files under `root`.

    Fail-closed: an entry resolving to ZERO files raises — a moved/renamed source
    blocks the build instead of silently dropping content from the brain.
    """
    files: list[Path] = []
    for entry in manifest:
        target = (root / entry).expanduser()
        if target.is_dir():
            found = sorted(target.rglob("*.md"))
            if not found:
                raise SystemExit(f"FAIL-CLOSED: manifest dir '{entry}' has no *.md under {root}")
            files.extend(found)
        elif target.is_file():
            files.append(target)
        else:
            raise SystemExit(f"FAIL-CLOSED: manifest entry '{entry}' not found under {root}")
    # de-dup, preserve order
    seen: set[Path] = set()
    unique = [f for f in files if not (f in seen or seen.add(f))]
    return unique


# ---------------------------------------------------------------------------
# 2. Assemble one big document with provenance headers
# ---------------------------------------------------------------------------


def assemble(files: list[Path], root: Path) -> str:
    stamp = datetime.now(timezone.utc).isoformat()
    parts: list[str] = [
        f"<!-- GENERATED by build_brain.py at {stamp} — DO NOT HAND-EDIT. "
        f"Edit the MANIFEST and re-run. {len(files)} source docs. -->\n"
    ]
    for f in files:
        rel = f.relative_to(root)
        parts.append(f"\n\n---\n\n<!-- SOURCE: {rel} -->\n# {rel}\n\n{f.read_text(encoding='utf-8')}")
    return "".join(parts)


def write_big_doc(text: str, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# 3. Ingest → chunk → embed → upsert into the kb Postgres coach corpus
#    (Phase 1 wiring — depends on the coach-corpus schema decision: reuse
#    reference_docs vs a coach-owned table. Left as the single TODO so the
#    pathways above are runnable today via --dry-run.)
# ---------------------------------------------------------------------------


def ingest(text: str) -> None:
    db_url = os.environ.get("COACH_DB_URL")
    embed_url = os.environ.get("EMBED_URL")
    if not db_url or not embed_url:
        raise SystemExit(
            "FAIL-FAST: ingest needs COACH_DB_URL + EMBED_URL. "
            "Run with --dry-run to assemble the big doc without ingesting."
        )
    # TODO(Phase 1): chunk(text) -> embed via shared-svcs (make_embed_token + EMBED_URL)
    #   -> UPSERT one reference_docs row titled CORPUS_TITLE + replace its
    #   reference_doc_chunks. Reuse the doc-ingestion utility pipeline; honor the
    #   coach-corpus schema decision (COACH_BRAIN §6). Idempotent on re-run.
    raise SystemExit("ingest() not wired yet — Phase 1. Use --dry-run for now.")


# ---------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the coach value-prop + stakeholder corpus from the THJ doc manifest.")
    ap.add_argument("--dry-run", action="store_true", help="assemble + write the big doc; skip ingest")
    ap.add_argument("--source-root", type=Path, default=SOURCE_ROOT, help=f"docs root (default {SOURCE_ROOT})")
    ap.add_argument("--output", type=Path, default=OUTPUT_PATH, help=f"assembled big-doc path (default {OUTPUT_PATH})")
    args = ap.parse_args()

    if not MANIFEST or all(not e.strip() for e in MANIFEST):
        print("MANIFEST is empty — nothing to build. Author the THJ doc paths in build_brain.py, then re-run.", file=sys.stderr)
        return 2

    if not args.source_root.is_dir():
        raise SystemExit(f"FAIL-CLOSED: source root not found: {args.source_root}")

    files = resolve_sources(MANIFEST, args.source_root)
    print(f"[build_brain] resolved {len(files)} source docs from {len(MANIFEST)} manifest entries")

    big_doc = assemble(files, args.source_root)
    write_big_doc(big_doc, args.output)
    print(f"[build_brain] wrote assembled corpus → {args.output} ({len(big_doc):,} chars)")

    if args.dry_run:
        print("[build_brain] --dry-run: skipping ingest")
        return 0

    ingest(big_doc)
    print(f"[build_brain] ingested → corpus '{CORPUS_TITLE}'")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
